# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerID', models.IntegerField()),
                ('Sponsor', models.CharField(max_length=64)),
                ('ServerName', models.CharField(max_length=64)),
                ('Timestamp', models.DateTimeField()),
                ('Distance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Ping', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Download', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Upload', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
